---
- name: Get distribution
  debug: msg="{{ ansible_distribution }}"

############################
# Install Docker on Ubuntu #
############################

- name: Install on Docker on CentOS
  block:
    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        pkg: "{{ item }}"
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
        - python3
        - python-pip

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Verify that we have the key with the fingerprint
      apt_key:
        id: 0EBFCD88
        state: present

    - name: Set up the stable Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        update_cache: yes

  when: ansible_facts['distribution'] == 'Ubuntu'

############################
# Install Docker on CentOS #
############################

- name: Install on Docker on CentOS
  block:
    - name: Install yum-utils, epel etc
      yum:
        name: "{{ item }}"
        update_cache: yes
        # state: absent
      loop:
        - yum-utils
        - epel-release
        - device-mapper-persistent-data
        - lvm2
        - python3-pip
        - python3
        - python-pip

        #################################
        # Add repository and GPG Docker #
        #################################

    - name: Add repository
      yum_repository:
        name: docker-ce.repo
        description: docker-ce.repo
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: yes
        gpgcheck: yes

    - name: Add Docker GPG key.
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

        ##################
        # Install Docker #
        ##################

  when: ansible_facts['distribution'] == 'CentOS'

########################
# Docker configuration #
########################

- name: Install new packages
  yum:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - docker-compose
    - containerd.io

- name: Add user to docker group
  user:
     name: "{{ ansible_user }}"
     group: docker

- name: Docker SDK for Python
  pip:
    name: docker

- name: Start and Enable service Docker
  service:
    name: docker
    state: started
    enabled: yes
